version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: cimg/node:17.1.0-browsers
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/dejang/dommy/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
workflows:
  test:
    jobs:
      - test

